trigger:
  branches:
    include:
      - main # Trigger on pushes to the main branch

pool:
  vmImage: 'ubuntu-latest' # Use a hosted agent with Ubuntu

steps:
- task: UseNode@2 # Install Node.js
  inputs:
    versionSpec: '18.x' # Specify the desired Node.js version

- script: |
    npm install # Install project dependencies
    npm test # Run tests
  displayName: 'Install dependencies and run tests'

- script: |
    npm run build # Build the Node.js project (if applicable)
  displayName: 'Build project'

- task: PublishPipelineArtifact@1 # Publish build artifacts
  inputs:
    artifactName: 'nodejs-app'
    pathToPublish: '$(Build.ArtifactStagingDirectory)' # Path to the compiled application
